name: Release
on:
  workflow_dispatch:

#--------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job-------------------

jobs:
  Semantic-version:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: merge
        run: |
          git checkot master
          git merge feature-101
          
