name: Release
on:
  workflow_dispatch:

#--------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job---------------------------------1st job-------------------

jobs:
  merge:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: merge
        run: |
          git pull --all
          git checkout feature-101
          git checkout master
          git merge feature-101
          
